@echo off
setlocal

pushd %~dp0
set script_dir=%CD%
cd ..
set PROJECT_ROOT=%CD%

:: this file is generated by CMake
del /q /f %PROJECT_ROOT%\include\csv\version.h > nul 2>&1

:: remove all log files from the tests directory
del /s /q /f %PROJECT_ROOT%\tests\*.log > nul 2>&1
