#!/bin/bash

# the clean directories are one directory up from the current path
# this process will also resolve symlinks if they exist on the path
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
# the resolved directory of this bash script
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# move up a level, then store the `pwd` as the project root variable
cd ..
PROJECT_ROOT=`pwd`

# echo $PROJECT_ROOT

# this file is generated by CMake
rm -f $PROJECT_ROOT/include/csv/version.h

# remove all log files from the tests directory
rm -f tests/*.log
