if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
  if(EXISTS "${CMAKE_SOURCE_DIR}/.git")
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY VALUE Debug)
  else()
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY VALUE Release)
  endif()
  message(STATUS "Setting build type to '${CMAKE_BUILD_TYPE}' as none was specified.")
endif()
