
if (NOT CSV_LOG_LEVEL)
  set(CSV_LOG_LEVEL "Debug" CACHE STRING "CSV Project testing log level" FORCE)
  if(${CMAKE_BUILD_TYPE} STREQUAL "Release" OR ${CMAKE_BUILD_TYPE} STREQUAL "RelWithDebInfo")
    set_property(CACHE CSV_LOG_LEVEL PROPERTY VALUE "Info")
  endif()
endif()

set_property(CACHE CSV_LOG_LEVEL PROPERTY STRINGS "None" "Fatal" "Error" "Warn" "Info" "Debug" "Verbose")

set(CSV_LOGGING_DEFINITION "" CACHE STRING "CSV Library logging compiler definition" FORCE)
mark_as_advanced(CSV_LOGGING_DEFINITION)

macro(csv_logging inputvar outputvar)
  if (${${inputvar}} STREQUAL "None")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_NONE)
  elseif (${${inputvar}} STREQUAL "Fatal")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_FATAL)
  elseif (${${inputvar}} STREQUAL "Error")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_ERROR)
  elseif (${${inputvar}} STREQUAL "Warn")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_WARN)
  elseif (${${inputvar}} STREQUAL "Info")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_INFO)
  elseif (${${inputvar}} STREQUAL "Debug")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_DEBUG)
  elseif (${${inputvar}} STREQUAL "Verbose")
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_VERBOSE)
  else()
    set_property(CACHE ${outputvar} PROPERTY VALUE ZF_LOG_DEBUG)
  endif()
  set_property(CACHE ${outputvar} PROPERTY STRINGS "ZF_LOG_NONE" "ZF_LOG_FATAL" "ZF_LOG_ERROR" "ZF_LOG_WARN" "ZF_LOG_INFO" "ZF_LOG_DEBUG" "ZF_LOG_VERBOSE")
endmacro(csv_logging)

csv_logging(CSV_LOG_LEVEL CSV_LOGGING_DEFINITION)
