
set(CSV_VERSION_MAJOR 0 CACHE STRING "CSV Project Version Major" FORCE)
set(CSV_VERSION_MINOR 1 CACHE STRING "CSV Project Version Minor" FORCE)
set(CSV_VERSION_PATCH 0 CACHE STRING "CSV Project Version Patch" FORCE)
set(CSV_VERSION_TWEAK 0 CACHE STRING "CSV Project Version Tweak" FORCE)

set(CSV_VERSION "${CSV_VERSION_MAJOR}.${CSV_VERSION_MINOR}.${CSV_VERSION_PATCH}.${CSV_VERSION_TWEAK}" CACHE STRING "CSV Project Full Version String" FORCE)
